+JobFlavour                   = "workday"
transfer_input_files          = /sphenix/u/bseidlitz/work/analysis/EMCal_pi0_Calib_2023/macros/condor/condorout/OutDir123/CondorRunJob.sh, /sphenix/u/bseidlitz/work/analysis/EMCal_pi0_Calib_2023/macros/condor/condorout/OutDir123/inputdata.txt,/sphenix/u/bseidlitz/work/analysis/EMCal_pi0_Calib_2023/macros/condor/condorout/OutDir123/Fun4All_EMCal_sp.C,/sphenix/u/bseidlitz/work/analysis/EMCal_pi0_Calib_2023/macros/condor/condorout/OutDir123/inputdatahits.txt
Executable                    = CondorRunJob.sh
request_memory                = 10GB
Universe                      = vanilla
Notification                  = Never
GetEnv                        = True
Priority                      = +12
Output                        = condor.out
Error                         = condor.err
Log                           = /tmp/condor.log
Notify_user                   = bs3402@columbia.edu

Queue
